<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.22" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gaya.Infrastructure\Gaya.Infrastructure.csproj" />
    <ProjectReference Include="..\Gaya.Application\Gaya.Application.csproj" />
    <ProjectReference Include="..\Gaya.Domain\Gaya.Domain.csproj" />
  </ItemGroup>

</Project>
